### PR TITLE
Fixed recipes for 4.0 rejectedPolicy.DiscardOldest removal

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://issues.apache.org/jira/browse/CAMEL-21131

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by oscerd** [comment]
@JiriOndrusek can you resolve conflicts? Thanks.

**Comment by davsclaus** [comment]
@JiriOndrusek is this PR still relevant, and if so, then can you work on fixing it

**Comment by JiriOndrusek** [comment]
The PR is still relevant, I fixed the conflict and now it can be merged.

**Comment by JiriOndrusek** [comment]
I accidentally did not commit all changes. The CI should pass now.

**Comment by davsclaus** [comment]
LGTM

**Pull request merged**
